# This workflow will run unit tests

name: Run Unit Tests
on:
  pull_request:
  workflow_dispatch:

jobs:
  py_build_tests:
    uses: neongeckocom/.github/.github/workflows/python_build_tests.yml@master
  unit_tests:
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . -r requirements/test_requirements.txt

      - name: Test Client
        run: |
          pytest tests/test_client.py --doctest-modules --junitxml=tests/client-test-results.xml
      - name: Upload client test results
        uses: actions/upload-artifact@v4
        with:
          name: client-test-results
          path: tests/client-test-results-${{ matrix.python-version }}.xml
